// COMENTEI O CODIGO - MAS SE QUISER GERAR PARA ALGUM TIPO PREDEFINOIDO
package main

// // Code generated by "stringer -type Key"; DO NOT EDIT.

// package main

// import "strconv"

// func _() {
// 	// An "invalid array index" compiler error signifies that the constant values have changed.
// 	// Re-run the stringer command to generate them again.
// 	var x [1]struct{}
// 	_ = x[Copper-1]
// 	_ = x[Jade-2]
// 	_ = x[Crystal-3]
// }

// const _Key_name = "CopperJadeCrystal"

// var _Key_index = [...]uint8{0, 6, 10, 17}

// func (i Key) String() string {
// 	i -= 1
// 	if i >= Key(len(_Key_index)-1) {
// 		return "Key(" + strconv.FormatInt(int64(i+1), 10) + ")"
// 	}
// 	return _Key_name[_Key_index[i]:_Key_index[i+1]]
// }
